steps:
  - label: ":hammer: Build"
    commands:
      - cd pyapp
      - pip3 install -r requirements.txt
    # plugins:
    #   - docker#v3.2.0:
    #       image: "python:3.12.8"
    #       workdir: /app
    artifact_paths:
      - "/usr/local/lib/python3.9/**"
    key: build
  - label: ":hammer: Test"
    commands:
      - cd pyapp
      - pip3 install -r requirements.txt
      - python3 main.py
    key: test