steps:
  - label: ":hammer: Clean"
    commands:
      - rm -rf /var/lib/buildkite-agent/.local/lib/python3.9/site-packages/
  - label: ":hammer: Build"
    commands:
      - cd pyapp
      - pip3 install -r requirements.txt
      # - find / -name "*ansi*" 2>/dev/null
    # plugins:
    #   - docker#v3.2.0:
    #       image: "python:3.12.8"
    #       workdir: /app
    artifact_paths:
      - "/var/lib/buildkite-agent/.local/lib/python3.9/**/*"
    key: build
  - label: ":hammer: Clean II"
    commands:
      - rm -rf /var/lib/buildkite-agent/.local/lib/python3.9/site-packages/
  - label: ":hammer: Test"
    commands:
      - cd pyapp
      - pip3 install -r requirements.txt
      - python3 main.py
    key: test