steps:
  - label: ":mag: Debug"
    command: |
      echo "Listing files in current directory:"
      ls -R
      echo "Current working directory:"
      pwd
  - label: ":hammer: Build"
    command: |
      if [ ! -f python/main.py ]; then
        echo "Error: python/main.py not found!"
        exit 1
      fi
      python python/main.py
